name: Prebuild rubies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: build rubies
      #   run: docker compose up
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: versions.tar.xz
      #     path: versions.tar.xz
