name: Release

on:
  workflow_run:
    workflows: ["Prebuild rubies"]
    branches: [main]
    types:
      - completed

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.23.0
        with:
          run_id: "${{ github.event.workflow_run.id }}"
          name: versions.tar.xz
      - name: Set datetime
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "${{ env.CURRENT_DATETIME }}"
          files: |
            versions.tar.xz
